# Generated by Django 4.2.15 on 2024-08-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='QuestionBank.field'),
        ),
    ]
